### ISSUE TITLE
Bank Text Entry Glitch

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#1]
when I select a bank to rename it, a few characters are being added after the name,  w, 1, and 2 when done is pressed, the characters disappear

![unknown](https://user-images.githubusercontent.com/10275421/164457700-c884d480-3f21-4d75-8601-d2762db18a1c.png)

![unknown](https://user-images.githubusercontent.com/10275421/164457636-58c6437c-da72-4042-81ad-d377327710e0.png)

![unknown](https://user-images.githubusercontent.com/10275421/164457730-55e85739-51e5-4ad7-97ca-01960cd0aa5d.png)

![image](https://user-images.githubusercontent.com/10275421/164457748-f1b7cefe-21d6-472b-8a67-3175ec761b99.png)

**Comment by AlphaMoonbaseBerlin** [comment]
It was the second on-skreen-keyboard. Simply disabling cooking or not importing it in to the project resolves the issue.
![grafik](https://user-images.githubusercontent.com/60106690/164636978-b839d4d5-2b99-4414-84d2-6b3b9ca0c41b.png)
