### ISSUE TITLE
Show Mode Switch

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#10]
the Show Mode switch needs to be connected to the display of the radio button of the mode bar

**Comment by AlphaMoonbaseBerlin** [comment]
fixed in https://github.com/AlphaMoonbaseBerlin/TauCeti-Presetsystem/commit/002fe3d4a9fba0d26ab9d24d5679a4acaad47bdd
