### ISSUE TITLE
Map search tags for dropdown update

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#11]
Currently the tag list in the dropdown of the map mode are not updating with the correct available tags:
![image](https://user-images.githubusercontent.com/10275421/169200699-2a5155c0-8b1e-4a2b-8e6c-118da41e1521.png)
not sure where its getting these two, but there are presets saved with the following tags:
![image](https://user-images.githubusercontent.com/10275421/169200818-ff36d030-cab3-410e-bdca-6e2f0d94cdcc.png)

**Comment by MacroMachines** [comment]
it would also be nice to style these widgets using the same rounded rectangle border and background color as the buttons and banks use :)

**Comment by AlphaMoonbaseBerlin** [comment]
Seems like an empty entry breaks the drop down menu. I removed all empty tags from the selection.:
https://github.com/AlphaMoonbaseBerlin/TauCeti-Presetsystem/commit/872cea7805565810e3a144cb101fe569d2f2eafa
