### ISSUE TITLE
Rename function not activating keyboard when name is "0" / blank / empty

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#13]
![image](https://user-images.githubusercontent.com/10275421/169202157-86722510-9040-47a6-8ccb-fece4ad3500d.png)
when clicking on a preset to name it, if the name is showing up as '0' the name can not be edited, the on-screen keyboard doesn't show up.
![image](https://user-images.githubusercontent.com/10275421/169202442-20ad0c60-7d70-425d-9ff1-2020dc6d7d0f.png)

**Comment by AlphaMoonbaseBerlin** [comment]
fixed in https://github.com/AlphaMoonbaseBerlin/TauCeti-Presetsystem/commit/002fe3d4a9fba0d26ab9d24d5679a4acaad47bdd
