### ISSUE TITLE
Highlite selected dashboard item

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#2]
current active slot hilight is sticking to on state 
![image](https://user-images.githubusercontent.com/10275421/164463637-ec76a41a-8b05-4560-8bea-bff629a9f712.png)

**Comment by AlphaMoonbaseBerlin** [comment]
Can you please confirm that you are using Version4 Build 37? I cannot reporduce this beahviour.

Try using the Map-Mode and clearing the stuck entries.
