### ISSUE TITLE
Auto Naming / Update Saved Data without rename

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#4]
with the record function auto-naming / save over the data:

if (there is currently already a named preset there) 
then (it needs to keep the name that was already there), 
else (generate numbered incremental name, referencing current names for highest number / calculating the number of settings correctly)

https://cdn.discordapp.com/attachments/846433870009073664/965450677214117938/IMG_8181.mov

**Comment by AlphaMoonbaseBerlin** [comment]
The system now is aware of the fact that a preset already exists. In this case, it will only update the values and thumbnail, not the name or tag.
It also hase seperated callbacks for that situations.
https://github.com/AlphaMoonbaseBerlin/TauCeti-Presetsystem/commit/d55f0f79fbc81611a6a9173a3962fe8f32d50fc0
