### ISSUE TITLE
Mapping Delete Function

### ISSUE THREAD

**Issue by MacroMachines** [AlphaMoonbaseBerlin/TauCeti-Presetsystem#6]
a delete button needs to be added to each preset in map mode, a small X like the bank list items have, in the top right of each item could work 
![image](https://user-images.githubusercontent.com/10275421/168631818-9ac9b44d-2a64-4621-94f0-a0183bf7ab68.png)
![image](https://user-images.githubusercontent.com/10275421/168632322-eef6388e-6bfa-4583-8b48-29bee122c8cb.png)

**Comment by AlphaMoonbaseBerlin** [comment]
![grafik](https://user-images.githubusercontent.com/60106690/170776913-819cb31d-0756-490b-bf7e-aa09575a8aab.png)

**Comment by AlphaMoonbaseBerlin** [comment]
https://github.com/AlphaMoonbaseBerlin/TauCeti-Presetsystem/commit/7a26b663ed503b6eff4b7d64292f69224af645db
